/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MacroEngine {
  constructor(path?: string | undefined | null)
  resolve(key: string): string | null
  add(key: string, command: string): boolean
  del(key: string): boolean
  list(): Array<Array<string>>
}

export declare class TaskManager {
  constructor(path?: string | undefined | null)
  createOnceTask(command: string, intervalMs: number): TaskEntry
  createLoopTask(command: string, intervalMs: number): TaskEntry
  listTasks(): Array<TaskEntry>
  removeTask(id: number): boolean
  clearTasks(): boolean
  setTaskEnabled(id: number, enabled: boolean): TaskEntry | null
  toggleScheduler(): boolean
  isSchedulerEnabled(): boolean
  advanceTask(id: number): TaskEntry | null
}

export interface TaskEntry {
  id: number
  command: string
  intervalMs: number
  nextRunMs: number
  mode: string
  enabled: boolean
}
