/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MacroEngine {
  constructor()
  resolve(key: string): string | null
  add(key: string, command: string): boolean
  del(key: string): boolean
  list(): Array<Array<string>>
}
